branches:
  only:
  - main
language: c
python:
- '3.6'
os:
- linux
- osx
addons:
  apt:
    update: true
    packages:
    - cmake
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - patchutils
    - bc
    - zlib1g-dev
    - libexpat-dev
    - libtool
    - pkg-config
    - mingw-w64
    - mingw-w64-tools
    - texlive
    - zip
    - python-dev
    - gettext
    - libglib2.0-dev
    - libpixman-1-dev
    - swig
    - ninja-build
    - python3
  homebrew:
    update: true
    packages:
    - cmake
    - autoconf
    - automake
    - gawk
    - gnu-sed
    - gnu-tar
    - texinfo
    - libtool
    - pkg-config
    - wget
    - xz
    - swig
    - python3
    - ninja
    - meson
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:deadsnakes/ppa
  -y ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -q ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3.6 python3.6-dev
  ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo update-alternatives --install /usr/bin/python3
  python3 /usr/bin/python3.6 10 ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo rm -rf /Library/Developer/CommandLineTools
  ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo xcode-select --install ; fi
- curl https://bootstrap.pypa.io/get-pip.py | python3
- pip3 install meson
script:
- patch -p0 < giturl.patch
- make openocd
